### ISSUE TITLE
我安装了这个软件，并且输入了自己的hostname,username和password，但是它没有任何反应

### ISSUE THREAD

**Issue by yiqifengfa** [kittoku/Open-SSTP-Client#1]

**Comment by kittoku** [comment]
1. Did you push `CONNECT` button?
2. Did a key icon show on the right side of the status bar? (it may takes several seconds to connect)
3. Did the app be killed without producing an error?
4. Did your hostname exclude `https://`?
5. Is the server [VPN Azure Cloud](https://www.vpnazure.net/)?

**Comment by yiqifengfa** [comment]
①There was no key icon on the right side of the status bar after I pressed the push button,And then the app doesn't crash or shut down.
②My server is not VPN Azure Cloud.

**Comment by kittoku** [comment]
Are you sure that you use SSTP protocol? This app is not for another protocol such as OpenVPN or L2TP/IPSec.

**Comment by yiqifengfa** [comment]
hi,master,What should I do if I add ms-chapv2 certification?

**Comment by kittoku** [comment]
This app allows only PAR authentication because it is simple to implement and secure enough to access VPN Azure Cloud, which is the reason why I made this app.

So you should change your authentication protocol to PAR.  Of course you can also fork this repository and add MS-CHAPv2 by yourself.

Sorry, but I cannot say for now that I will add it.
