### ISSUE TITLE
"reset setting to default" button

### ISSUE THREAD

**Issue by shakibamoshiri** [kittoku/Open-SSTP-Client#100]
Using this app for a while and suggesting it to other to use, I noticed after a while many people which face issue connecting to a VPN server, they start changing options in "SETTING" tab and will have hard time resting to default setting. So a **button** which could reset setting to default could be useful.
Regards

**Comment by kittoku** [comment]
The feature has been implemented in v1.6.5. Please use `Reload Defaults` button in the option menu.

**Comment by shakibamoshiri** [comment]
@kittoku I updated and tested the app, sure it resets the SETTING to default but HOME part as well which means a user has to do ether ways 
- Save Profile  (backup)
- Reload Default (reset)
- Reload Profile  (restore)

or
- Reload Profile (reset)
- manually entering credentials (restore)

the ideal would be reset the SETTING tab not HOME one.

**Comment by kittoku** [comment]
Technically speaking, a credential also is treated as setting. So I thought resetting values in `HOME`  tab as well is good for most cases (not best for a specific case). Above all, this way needed a small code change.

**Comment by Jamalsaeeid5** [comment]
Life is beautiful everywhereاز گوشی هوشمند Samsung Galaxy ارسال شده است.
-------- پیام اصلی --------از: KOBAYASHI Ittoku ***@***.***> تاریخ: ۲۰۲۳/۸/۱۲  ۱۲:۱۷ ب.ظ  (GMT+03:30) گیرنده: kittoku/Open-SSTP-Client ***@***.***> گیرنده کپی: Subscribed ***@***.***> موضوع Re: [kittoku/Open-SSTP-Client] "reset setting to default" button (Issue #100) 
Technically speaking, a credential also is treated as setting. So I thought resetting values in HOME  tab as well is good for most cases (not best for a specific case). Above all, this way needed a small code change.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/kittoku/Open-SSTP-Client/issues/100#issuecomment-1675797650",
"url": "https://github.com/kittoku/Open-SSTP-Client/issues/100#issuecomment-1675797650",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
