### ISSUE TITLE
Mikrotik SSTP does not works

### ISSUE THREAD

**Issue by bigmoveus** [kittoku/Open-SSTP-Client#124]
Hi , I try to connect by SSTP client to Mikrotik OS SSTP Server . and it could not connect at all . i could share the server details so can try

**Comment by falciloid** [comment]
Can you share config from routeros that you use as a server? Do `/export terse file=exp` in terminal, than grab it to your PC, wipe unnecessary data and post here. Maybe your server setup is incorrect

**Comment by schneis** [comment]
FWIW, I've tried to get this app to connect to a Mikrotik SSTP VPN server many times and could never get it to connect (Mikrotik SSTP servers using both a LetsEncrypt signed certificate as well as a self signed certificate).
The SSTP Max app was able to connect for a while, but something has happened and even it can't connect. I converted my client to OpenVPN to get them working again.
If the app author needs a Mikrotik SSTP server to test against, I may be able to set something up.

**Comment by Lik2729aysk** [comment]
Hola necesito ayuda para configurar mi mikrotik para usar la app

**Comment by james-bond-sudo** [comment]
LetsEncrypt certificate, ver 1.7.1
[log_osc_20240315164632.txt](https://github.com/kittoku/Open-SSTP-Client/files/14616329/log_osc_20240315164632.txt)

**Comment by KriBielinski** [comment]
I managed to connect to Mikrotik router. One thing I can say is to switch "TLS Version" in routeros to 'any' (even if you are actually using TLSv1.2 in the app to connect). Another thing is to disable the "Verify Hostname" checkbox in the App settings (now this may just be problem on my side, because I use self-signed certificate on the server, but I was not able to connect with this option on). Also in PPP profile settings in routeros make sure you fill local and remote address fields, otherwise there will be no IP connectivity between the client and the server.
