### ISSUE TITLE
SoftEther gang here to see if this is still active 

### ISSUE THREAD

**Issue by NineBallAYAYA** [kittoku/Open-SSTP-Client#5]
any chance this could get support for servers other than azure? I run a sstp server on a raspi in my basement and would very much like if i could connect to it with this...

**Comment by kittoku** [comment]
I only support VPN azure cloud because accessing to it was my goal and decrypting(debugging) it is easy in my environment.

Still, I have a plan to make some improvements of this app like catching decrypted packets from ssl socket and faking a pcap file to debug for all environments. But I cannot say now when to update. 

BTW, you already tried this app on your raspi?

**Comment by NineBallAYAYA** [comment]
The raspi is the sstp server using softether. I want to run this client on my android so that I can connect with my laptop and phone.

If you don't understand here is the site
https://www.softether.org

**Comment by kittoku** [comment]
You also tried filling `Host` with your server's ip address?

**Comment by NineBallAYAYA** [comment]
yep, it just flashes in the icons list at the top then disappears.

**Comment by kittoku** [comment]
Thank you for reporting. I can come up with three options, 

1. If your server has a self-signed certificate, installing that certificate to you device may be solve the crash.
2. You can choose an alternative VPN protocol, such as OpenVPN. Android has many apps for it.
3. (not recommend) you wait for my improvement.

Sorry for the inconvenience.

**Comment by NineBallAYAYA** [comment]
Yea still crashes thanks for the help though I guess I will be waiting
